import "./globals.css";
import "./Font.css"
import Scroll from "@/Components/Scroll";



export const metadata = {
  title: "Artisticks",
  description: "Generated by create next app",
  manifest: '/manifest.json',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        suppressHydrationWarning
      >
        {children}
        <Scroll />
      </body>
    </html>
  );
}
